name: MyPy Checker
on: [push]
jobs:
  MyPy-Type-Checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install mypy
        run: |
          sudo apt install mypy
      - name: Run mypy against all files
        run: |
          mypy *.py

